name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
      
      - name: Debug build directory
        run: |
          echo "Listing build directory structure:"
          ls -la build
          ls -la build/client || echo "build/client does not exist"
          
      - name: Prepare for deployment
        run: |
          # Add .nojekyll file to bypass Jekyll processing
          touch build/client/.nojekyll
          
          # Copy 200.html to index.html if it exists
          if [ -f build/client/200.html ]; then
            cp build/client/200.html build/client/index.html
            echo "Created index.html from 200.html"
          else
            echo "Creating a basic index.html"
            echo "<!DOCTYPE html><html><head><meta http-equiv='refresh' content='0;url=/react-remix-form-builder/'></head><body>Redirecting...</body></html>" > build/client/index.html
          fi
          
          # List contents to verify
          echo "Contents of build/client directory:"
          ls -la build/client
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/client
          branch: gh-pages
          clean: true
